name: Create Branch from Issue

on:
  issues:
    types: [opened]

jobs:
  create_branch:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.ACTIONS_DEPLOY_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan github.com >> ~/.ssh/known_hosts

    - name: Create branch
      run: |
        ISSUE_NUMBER=$(echo "${{ github.event.issue.number }}")
        ISSUE_TITLE=$(echo "${{ github.event.issue.title }}" | sed 's/ /-/g' | tr '[:upper:]' '[:lower:]')
        BRANCH_NAME="issue-${ISSUE_NUMBER}-${ISSUE_TITLE}"
        
        # Dynamically set git config with actor's username and a no-reply email
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@gmail.com"
        
        # Create and push the branch
        git checkout -b $BRANCH_NAME
        git remote set-url origin git@github.com:Darkwing-Duck-Tamagotchi/kraken-kritters.git
        git push origin $BRANCH_NAME

    - name: Comment on the issue
      run: |
        ISSUE_NUMBER=$(echo "${{ github.event.issue.number }}")
        BRANCH_NAME="issue-${ISSUE_NUMBER}-${ISSUE_TITLE}"
        
        # Post a comment on the issue
        curl -X POST \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{"body":"Branch created: `'"$BRANCH_NAME"'`"}' \
          https://api.github.com/repos/${{ github.repository }}/issues/${ISSUE_NUMBER}/comments
